package com.javanei.emulation.common.game;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

/**
 * @author Vanei
 * 
 * @see https://pt.wikipedia.org/wiki/Lista_de_jogos_para_Sega_CD
 * @see http://gamesdbase.com/list.aspx
 * @see http://www.oldgamesfinder.com/
 */
public class GamePublisher implements Serializable {

    private static final long serialVersionUID = 1L;

    private static final Map<String, GamePublisher> publishers = new HashMap<>();
    private final String publisher;

    static {
        publishers.put("21st Century Entertainment", new GamePublisher("21st Century Entertainment"));
        publishers.put("21st Century Entertainment Ltd.", new GamePublisher("21st Century Entertainment Ltd."));
        publishers.put("A & F Software", new GamePublisher("A & F Software"));
        publishers.put("A&F Software", new GamePublisher("A&F Software"));
        publishers.put("A.L.Dukes", new GamePublisher("A.L.Dukes"));
        publishers.put("Abbex", new GamePublisher("Abbex"));
        publishers.put("Abbex Software", new GamePublisher("Abbex"));
        publishers.put("Abrasco Ltd.", new GamePublisher("Abrasco Ltd."));
        publishers.put("Access Software", new GamePublisher("Access Software"));
        publishers.put("Accolade", new GamePublisher("Accolade"));
        publishers.put("Acme Software Ltd.", new GamePublisher("Acme Software Ltd."));
        publishers.put("Activision", new GamePublisher("Activision"));
        publishers.put("Activision / Sega", new GamePublisher("Activision / Sega"));
        publishers.put("Activision Inc.", new GamePublisher("Activision"));
        publishers.put("Addictive Games", new GamePublisher("Addictive Games"));
        publishers.put("Addictive Games Ltd.", new GamePublisher("Addictive Games Ltd."));
        publishers.put("Advanced Computer Entertainment", new GamePublisher("Advanced Computer Entertainment"));
        publishers.put("Advantage*Artworx", new GamePublisher("Advantage*Artworx"));
        publishers.put("Adventuresoft", new GamePublisher("Adventuresoft"));
        publishers.put("Alligata", new GamePublisher("Alligata"));
        publishers.put("Alligata Software", new GamePublisher("Alligata"));
        publishers.put("Alligata Software Ltd.", new GamePublisher("Alligata"));
        publishers.put("Alternative", new GamePublisher("Alternative"));
        publishers.put("Alternative Software", new GamePublisher("Alternative"));
        publishers.put("Alternative Software / Enigma Variations", new GamePublisher("Alternative Software / Enigma Variations"));
        publishers.put("Alternative Software Ltd.", new GamePublisher("Alternative"));
        publishers.put("American Action", new GamePublisher("American Action"));
        publishers.put("Americana", new GamePublisher("Americana"));
        publishers.put("Americana Software", new GamePublisher("Americana"));
        publishers.put("Anco", new GamePublisher("Anco"));
        publishers.put("Anco Software Ltd.", new GamePublisher("Anco"));
        publishers.put("Andromeda", new GamePublisher("Andromeda"));
        publishers.put("Andromeda Software", new GamePublisher("Andromeda"));
        publishers.put("Anik Micro Systems", new GamePublisher("Anik Micro Systems"));
        publishers.put("Anirog", new GamePublisher("Anirog"));
        publishers.put("Anirog Software", new GamePublisher("Anirog"));
        publishers.put("Applications Software Specialists", new GamePublisher("Applications Software Specialists"));
        publishers.put("Argus Press Software", new GamePublisher("Argus Press Software"));
        publishers.put("Argus Press Software Ltd.", new GamePublisher("Argus Press Software Ltd."));
        publishers.put("Ariolasoft", new GamePublisher("Ariolasoft"));
        publishers.put("Ariolasoft (Electronic Arts)", new GamePublisher("Ariolasoft (Electronic Arts)"));
        publishers.put("Ariolasoft Ltd.", new GamePublisher("Ariolasoft"));
        publishers.put("Ariolasoft UK Ltd.", new GamePublisher("Ariolasoft UK Ltd."));
        publishers.put("Artic Computing", new GamePublisher("Artic Computing"));
        publishers.put("Artronic Products Ltd.", new GamePublisher("Artronic Products Ltd."));
        publishers.put("Artworx", new GamePublisher("Artworx"));
        publishers.put("Artworx Software Company", new GamePublisher("Artworx"));
        publishers.put("Atarisoft", new GamePublisher("Atarisoft"));
        publishers.put("Atlantis", new GamePublisher("Atlantis"));
        publishers.put("Atlantis Software", new GamePublisher("Atlantis"));
        publishers.put("Atlantis Software Ltd.", new GamePublisher("Atlantis"));
        publishers.put("Audiogenic", new GamePublisher("Audiogenic"));
        publishers.put("Audiogenic Software Ltd.", new GamePublisher("Audiogenic Software Ltd."));
        publishers.put("Aventuras AD", new GamePublisher("Aventuras AD"));
        publishers.put("Beyond", new GamePublisher("Beyond"));
        publishers.put("Beyond Belief", new GamePublisher("Beyond Belief"));
        publishers.put("Beyond Software", new GamePublisher("Beyond Software"));
        publishers.put("Big G", new GamePublisher("Big G"));
        publishers.put("Blue Ribbon Software", new GamePublisher("Blue Ribbon Software"));
        publishers.put("Brøderbund", new GamePublisher("Brøderbund"));
        publishers.put("Bubble Bus", new GamePublisher("Bubble Bus"));
        publishers.put("Bubble Bus Software", new GamePublisher("Bubble Bus Software"));
        publishers.put("Bubblebus", new GamePublisher("Bubblebus"));
        publishers.put("Bubblebus Software", new GamePublisher("Bubblebus"));
        publishers.put("Bug Byte", new GamePublisher("Bug Byte"));
        publishers.put("Bug-Byte", new GamePublisher("Bug-Byte"));
        publishers.put("Bug-Byte Software", new GamePublisher("Bug-Byte Software"));
        publishers.put("Bug-Byte Software Ltd.", new GamePublisher("Bug-Byte Software Ltd."));
        publishers.put("Bulldog", new GamePublisher("Bulldog"));
        publishers.put("Bulldog Software (Mastertronic)", new GamePublisher("Bulldog"));
        publishers.put("Bulldog Software / Mastertronic", new GamePublisher("Bulldog"));
        publishers.put("Byte Back", new GamePublisher("Byte Back"));
        publishers.put("Byte-Back", new GamePublisher("Byte-Back"));
        publishers.put("Byteback", new GamePublisher("Byteback"));
        publishers.put("CDS", new GamePublisher("CDS"));
        publishers.put("CDS Software", new GamePublisher("CDS"));
        publishers.put("CDS Software Ltd.", new GamePublisher("CDS"));
        publishers.put("CP Software", new GamePublisher("CP Software"));
        publishers.put("CRL", new GamePublisher("CRL"));
        publishers.put("Cable Software Ltd.", new GamePublisher("Cable Software Ltd."));
        publishers.put("Capcom", new GamePublisher("Capcom"));
        publishers.put("Capcom / Kixx", new GamePublisher("Capcom / Kixx"));
        publishers.put("Capcom/Software Creations", new GamePublisher("Capcom/Software Creations"));
        publishers.put("Cascade Games Ltd.", new GamePublisher("Cascade Games Ltd."));
        publishers.put("Challenge Software", new GamePublisher("Challenge Software"));
        publishers.put("Channel 8 Software", new GamePublisher("Channel 8 Software"));
        publishers.put("CodeMasters Ltd.", new GamePublisher("Codemasters"));
        publishers.put("Codemasters", new GamePublisher("Codemasters"));
        publishers.put("Codemasters (Viz Design)", new GamePublisher("Codemasters"));
        publishers.put("Collins Software", new GamePublisher("Collins Software"));
        publishers.put("Comm*Data", new GamePublisher("Comm*Data"));
        publishers.put("Commercial Data Systems", new GamePublisher("Commercial Data Systems"));
        publishers.put("Commodore", new GamePublisher("Commodore"));
        publishers.put("Commodore Business Machines (UK) Ltd.", new GamePublisher("Commodore Business Machines (UK) Ltd."));
        publishers.put("Cosmi", new GamePublisher("Cosmi"));
        publishers.put("Creative Sparks", new GamePublisher("Creative Sparks"));
        publishers.put("Creative Sparks (Thorn EMI Computer Software)", new GamePublisher("Creative Sparks (Thorn EMI Computer Software)"));
        publishers.put("Cult Games", new GamePublisher("Cult Games"));
        publishers.put("D&H Games", new GamePublisher("D&H Games"));
        publishers.put("Data Computer House", new GamePublisher("Data Computer House"));
        publishers.put("Data East", new GamePublisher("Data East"));
        publishers.put("Database Software", new GamePublisher("Database Software"));
        publishers.put("Databyte", new GamePublisher("Databyte"));
        publishers.put("Databyte Ltd.", new GamePublisher("Databyte Ltd."));
        publishers.put("Datasoft", new GamePublisher("Datasoft"));
        publishers.put("Datasoft Inc.", new GamePublisher("Datasoft Inc."));
        publishers.put("Demonware", new GamePublisher("Demonware"));
        publishers.put("Destiny Software Ltd.", new GamePublisher("Destiny Software Ltd."));
        publishers.put("Digital Integration", new GamePublisher("Digital Integration"));
        publishers.put("Digital Intergration", new GamePublisher("Digital Intergration"));
        publishers.put("Dinamic", new GamePublisher("Dinamic"));
        publishers.put("Dinamic Software", new GamePublisher("Dinamic Software"));
        publishers.put("Disney Software", new GamePublisher("Disney Software"));
        publishers.put("Dk'Tronics Ltd.", new GamePublisher("Dk'Tronics Ltd."));
        publishers.put("Doctor Soft", new GamePublisher("Doctor Soft"));
        publishers.put("Domark", new GamePublisher("Domark"));
        publishers.put("Domark / Incentive", new GamePublisher("Domark / Incentive"));
        publishers.put("Domark / Tengen", new GamePublisher("Domark / Tengen"));
        publishers.put("Domark/Tengen", new GamePublisher("Domark/Tengen"));
        publishers.put("Dro Soft", new GamePublisher("Dro Soft"));
        publishers.put("Durell Software", new GamePublisher("Durell Software"));
        publishers.put("Dynavision Productions", new GamePublisher("Dynavision Productions"));
        publishers.put("E&J Software", new GamePublisher("E&J Software"));
        publishers.put("Edge, The", new GamePublisher("Edge, The"));
        publishers.put("Electric Dreams", new GamePublisher("Electric Dreams"));
        publishers.put("Electric Dreams Software", new GamePublisher("Electric Dreams"));
        publishers.put("Electronic Arts", new GamePublisher("Electronic Arts"));
        publishers.put("Elite", new GamePublisher("Elite"));
        publishers.put("Elite / Hit-Pak", new GamePublisher("Elite / Hit-Pak"));
        publishers.put("Elite Systems Ltd.", new GamePublisher("Elite Systems Ltd."));
        publishers.put("Elite Systems Ltd. (Encore)", new GamePublisher("Elite Systems Ltd. (Encore)"));
        publishers.put("Empire", new GamePublisher("Empire"));
        publishers.put("Encore", new GamePublisher("Encore"));
        publishers.put("Encore (Elite Systems Ltd)", new GamePublisher("Encore (Elite Systems Ltd)"));
        publishers.put("Encore (Elite Systems Ltd.)", new GamePublisher("Encore (Elite Systems Ltd.)"));
        publishers.put("Endurance Games", new GamePublisher("Endurance Games"));
        publishers.put("English Software", new GamePublisher("English Software"));
        publishers.put("English Software Company", new GamePublisher("English Software Company"));
        publishers.put("Enigma Variations", new GamePublisher("Enigma Variations"));
        publishers.put("Entertainment USA (Mastertronic)", new GamePublisher("Entertainment USA (Mastertronic)"));
        publishers.put("Epyx", new GamePublisher("Epyx"));
        publishers.put("Erbe Software", new GamePublisher("Erbe Software"));
        publishers.put("Eurogold", new GamePublisher("Eurogold"));
        publishers.put("Faster Than Light", new GamePublisher("Faster Than Light"));
        publishers.put("Firebird", new GamePublisher("Firebird"));
        publishers.put("Firebird (Activision)", new GamePublisher("Firebird (Activision)"));
        publishers.put("Firebird / Odin Computer Graphics", new GamePublisher("Firebird / Odin Computer Graphics"));
        publishers.put("Firebird / Ultimate", new GamePublisher("Firebird / Ultimate"));
        publishers.put("Firebird Software", new GamePublisher("Firebird"));
        publishers.put("First Star Software", new GamePublisher("First Star Software"));
        publishers.put("Flair Software", new GamePublisher("Flair Software"));
        publishers.put("Flair Software Ltd.", new GamePublisher("Flair Software Ltd."));
        publishers.put("Front Runner", new GamePublisher("Front Runner"));
        publishers.put("Funsoft, Inc.", new GamePublisher("Funsoft, Inc."));
        publishers.put("GTI Software", new GamePublisher("GTI Software"));
        publishers.put("Galactic Software", new GamePublisher("Galactic Software"));
        publishers.put("Go!", new GamePublisher("Go!"));
        publishers.put("Go! (U.S. Gold)", new GamePublisher("Go! (U.S. Gold)"));
        publishers.put("Go! (US Gold)", new GamePublisher("Go! (US Gold)"));
        publishers.put("Golden Games", new GamePublisher("Golden Games"));
        publishers.put("Goliath Games", new GamePublisher("Goliath Games"));
        publishers.put("Graftgold", new GamePublisher("Graftgold"));
        publishers.put("Graftgold / Firebird", new GamePublisher("Graftgold / Firebird"));
        publishers.put("Grandslam", new GamePublisher("Grandslam"));
        publishers.put("Grandslam Entertainment Ltd.", new GamePublisher("Grandslam Entertainment Ltd."));
        publishers.put("Gremlin Graphics", new GamePublisher("Gremlin Graphics"));
        publishers.put("Gremlin Graphics Software Ltd.", new GamePublisher("Gremlin Graphics Software Ltd."));
        publishers.put("HITECH Games Plus", new GamePublisher("HITECH Games Plus"));
        publishers.put("Hewson", new GamePublisher("Hewson"));
        publishers.put("Hewson Consultants", new GamePublisher("Hewson Consultants"));
        publishers.put("Hewson Consultants Ltd.", new GamePublisher("Hewson Consultants Ltd."));
        publishers.put("Hewson Consultants Ltd. / Graftgold", new GamePublisher("Hewson Consultants Ltd. / Graftgold"));
        publishers.put("Hi TEC Software Ltd.", new GamePublisher("Hi TEC Software Ltd."));
        publishers.put("Hi-TEC Software Ltd.", new GamePublisher("Hi-TEC Software Ltd."));
        publishers.put("Hi-Tec Software", new GamePublisher("Hi-Tec Software"));
        publishers.put("Hi-Tec Software Ltd.", new GamePublisher("Hi-Tec Software Ltd."));
        publishers.put("Hit Squad", new GamePublisher("Hit Squad"));
        publishers.put("Hit Squad (Ocean)", new GamePublisher("Hit Squad (Ocean)"));
        publishers.put("Hit-Pak", new GamePublisher("Hit-Pak"));
        publishers.put("Hit-Squad", new GamePublisher("Hit-Squad"));
        publishers.put("HitSquad (Imagine)", new GamePublisher("HitSquad (Imagine)"));
        publishers.put("Hitech Games Plus", new GamePublisher("Hitech Games Plus"));
        publishers.put("I.J.K. Software", new GamePublisher("I.J.K. Software"));
        publishers.put("IJK Software Ltd.", new GamePublisher("IJK Software Ltd."));
        publishers.put("Image Works", new GamePublisher("Image Works"));
        publishers.put("Imageworks", new GamePublisher("Imageworks"));
        publishers.put("Imageworks (Mirrorsoft)", new GamePublisher("Imageworks (Mirrorsoft)"));
        publishers.put("Imageworks Ltd.", new GamePublisher("Imageworks Ltd."));
        publishers.put("Imagine", new GamePublisher("Imagine"));
        publishers.put("Imagine / Dinamic", new GamePublisher("Imagine / Dinamic"));
        publishers.put("Imagine / Konami", new GamePublisher("Imagine / Konami"));
        publishers.put("Imagine Software", new GamePublisher("Imagine"));
        publishers.put("Impressions", new GamePublisher("Impressions"));
        publishers.put("Impulze", new GamePublisher("Impulze"));
        publishers.put("Incentive Software", new GamePublisher("Incentive Software"));
        publishers.put("Infogrames", new GamePublisher("Infogrames"));
        publishers.put("Interceptor Software", new GamePublisher("Interceptor Software"));
        publishers.put("Ivan Berg Software Ltd.", new GamePublisher("Ivan Berg Software Ltd."));
        publishers.put("J Morrison Micros Ltd.", new GamePublisher("J Morrison Micros Ltd."));
        publishers.put("J. Morrison Ltd.", new GamePublisher("J. Morrison Ltd."));
        publishers.put("Johnson Scanatron Ltd.", new GamePublisher("Johnson Scanatron Ltd."));
        publishers.put("K-Tel International Ltd.", new GamePublisher("K-Tel International Ltd."));
        publishers.put("Kele Line", new GamePublisher("Kele Line"));
        publishers.put("Kingsoft", new GamePublisher("Kingsoft"));
        publishers.put("Kixx", new GamePublisher("Kixx"));
        publishers.put("Budget - Kixx", new GamePublisher("Budget - Kixx"));
        publishers.put("Konami", new GamePublisher("Konami"));
        publishers.put("Krypton Force", new GamePublisher("Krypton Force"));
        publishers.put("Leisure Genius", new GamePublisher("Leisure Genius"));
        publishers.put("Level 9 Computing", new GamePublisher("Level 9 Computing"));
        publishers.put("Level 9 Software", new GamePublisher("Level 9 Software"));
        publishers.put("Livewire", new GamePublisher("Livewire"));
        publishers.put("Livewire Software Ltd.", new GamePublisher("Livewire Software Ltd."));
        publishers.put("Llama Software", new GamePublisher("Llama Software"));
        publishers.put("Llamasoft", new GamePublisher("Llamasoft"));
        publishers.put("Llamasoft Software", new GamePublisher("Llamasoft Software"));
        publishers.put("Logotron", new GamePublisher("Logotron"));
        publishers.put("Lothlorien", new GamePublisher("Lothlorien"));
        publishers.put("Lucasfilm", new GamePublisher("Lucasfilm"));
        publishers.put("Lucasfilm Games", new GamePublisher("Lucasfilm"));
        publishers.put("MAD Games", new GamePublisher("MAD Games"));
        publishers.put("MC Lothlorien", new GamePublisher("MC Lothlorien"));
        publishers.put("MCM", new GamePublisher("MCM"));
        publishers.put("MCM Software", new GamePublisher("MCM"));
        publishers.put("Macsen Software", new GamePublisher("Macsen Software"));
        publishers.put("Magic Bytes", new GamePublisher("Magic Bytes"));
        publishers.put("Martech", new GamePublisher("Martech"));
        publishers.put("Mastertronic", new GamePublisher("Mastertronic"));
        publishers.put("Mastertronic (Bulldog)", new GamePublisher("Mastertronic (Bulldog)"));
        publishers.put("Mastertronic (Dinamic)", new GamePublisher("Mastertronic (Dinamic)"));
        publishers.put("Mastertronic (M.A.D.)", new GamePublisher("Mastertronic (M.A.D.)"));
        publishers.put("Mastertronic (MAD)", new GamePublisher("Mastertronic (MAD)"));
        publishers.put("Mastertronic (Melbourne House)", new GamePublisher("Mastertronic (Melbourne House)"));
        publishers.put("Mastertronic (Mr. Chip)", new GamePublisher("Mastertronic (Mr. Chip)"));
        publishers.put("Mastertronic (Ricochet)", new GamePublisher("Mastertronic (Ricochet)"));
        publishers.put("Mastertronic Added Dimension", new GamePublisher("Mastertronic Added Dimension"));
        publishers.put("Mastertronic Ltd. (Mastertronic Plus)", new GamePublisher("Mastertronic Ltd. (Mastertronic Plus)"));
        publishers.put("Mastertronic Plus", new GamePublisher("Mastertronic Plus"));
        publishers.put("Melbourne House", new GamePublisher("Melbourne House"));
        publishers.put("Melbourne House / Beam Software", new GamePublisher("Melbourne House / Beam Software"));
        publishers.put("Melbourne House / Psygnosis", new GamePublisher("Melbourne House / Psygnosis"));
        publishers.put("Merlin Software", new GamePublisher("Merlin Software"));
        publishers.put("Micro Power", new GamePublisher("Micro Power"));
        publishers.put("Micro Selection Plus", new GamePublisher("Micro Selection Plus"));
        publishers.put("MicroProse", new GamePublisher("MicroProse"));
        publishers.put("MicroProse Software", new GamePublisher("MicroProse Software"));
        publishers.put("MicroValue", new GamePublisher("MicroValue"));
        publishers.put("Micromania", new GamePublisher("Micromania"));
        publishers.put("Micromega", new GamePublisher("Micromega"));
        publishers.put("Micropool", new GamePublisher("Micropool"));
        publishers.put("Microprose", new GamePublisher("Microprose"));
        publishers.put("Microprose Software", new GamePublisher("Microprose Software"));
        publishers.put("Microsphere", new GamePublisher("Microsphere"));
        publishers.put("Microstyle", new GamePublisher("Microstyle"));
        publishers.put("Microvalue", new GamePublisher("Microvalue"));
        publishers.put("Mike Singleton", new GamePublisher("Mike Singleton"));
        publishers.put("Millenium", new GamePublisher("Millenium"));
        publishers.put("Millennium", new GamePublisher("Millennium"));
        publishers.put("Mind Games", new GamePublisher("Mind Games"));
        publishers.put("Mindscape", new GamePublisher("Mindscape"));
        publishers.put("Mindscape Inc.", new GamePublisher("Mindscape Inc."));
        publishers.put("Mindscape, Inc.", new GamePublisher("Mindscape, Inc."));
        publishers.put("Mindscape, Inc. / Light Fantastic", new GamePublisher("Mindscape, Inc. / Light Fantastic"));
        publishers.put("Mirrorsoft", new GamePublisher("Mirrorsoft"));
        publishers.put("Mirrorsoft Ltd.", new GamePublisher("Mirrorsoft Ltd."));
        publishers.put("Mogul Communications Ltd.", new GamePublisher("Mogul Communications Ltd."));
        publishers.put("Mosaic Publishing", new GamePublisher("Mosaic Publishing"));
        publishers.put("Mr. Chip Software", new GamePublisher("Mr. Chip Software"));
        publishers.put("Mr. Micro", new GamePublisher("Mr. Micro"));
        publishers.put("New Generation Software", new GamePublisher("New Generation Software"));
        publishers.put("Nexus", new GamePublisher("Nexus"));
        publishers.put("Novagen Software", new GamePublisher("Novagen Software"));
        publishers.put("Ocean", new GamePublisher("Ocean"));
        publishers.put("Ocean (Activision)", new GamePublisher("Ocean (Activision)"));
        publishers.put("Ocean (Incentive Software)", new GamePublisher("Ocean (Incentive Software)"));
        publishers.put("Ocean / Data East", new GamePublisher("Ocean / Data East"));
        publishers.put("Ocean / Special FX", new GamePublisher("Ocean / Special FX"));
        publishers.put("Ocean Software", new GamePublisher("Ocean"));
        publishers.put("Ocean Software Ltd", new GamePublisher("Ocean"));
        publishers.put("Ocean Software Ltd.", new GamePublisher("Ocean"));
        publishers.put("Odin Computer Graphics", new GamePublisher("Odin Computer Graphics"));
        publishers.put("Odin Computer Graphics Ltd.", new GamePublisher("Odin Computer Graphics Ltd."));
        publishers.put("PSS", new GamePublisher("PSS"));
        publishers.put("PSS (Personal Software Services)", new GamePublisher("PSS (Personal Software Services)"));
        publishers.put("Pal Developments", new GamePublisher("Pal Developments"));
        publishers.put("Palace", new GamePublisher("Palace"));
        publishers.put("Palace Software", new GamePublisher("Palace"));
        publishers.put("Pandora", new GamePublisher("Pandora"));
        publishers.put("Paramount Software", new GamePublisher("Paramount Software"));
        publishers.put("Paxman Promotions", new GamePublisher("Paxman Promotions"));
        publishers.put("Penguin Software", new GamePublisher("Penguin Software"));
        publishers.put("Personal Software Services", new GamePublisher("Personal Software Services"));
        publishers.put("Piranha", new GamePublisher("Piranha"));
        publishers.put("Piranha Software", new GamePublisher("Piranha Software"));
        publishers.put("Players", new GamePublisher("Players"));
        publishers.put("Players Premier", new GamePublisher("Players Premier"));
        publishers.put("Players Software", new GamePublisher("Players Software"));
        publishers.put("Power House", new GamePublisher("Power House"));
        publishers.put("Prism Leisure", new GamePublisher("Prism Leisure"));
        publishers.put("Prism Leisure Corporation", new GamePublisher("Prism Leisure Corporation"));
        publishers.put("Probe Software", new GamePublisher("Probe Software"));
        publishers.put("Proein Softline", new GamePublisher("Proein Softline"));
        publishers.put("Psyclapse", new GamePublisher("Psyclapse"));
        publishers.put("Psyclapse/Psygnosis", new GamePublisher("Psyclapse/Psygnosis"));
        publishers.put("Psygnosis", new GamePublisher("Psygnosis"));
        publishers.put("Quicksilva", new GamePublisher("Quicksilva"));
        publishers.put("Quicksilva (Argus Press Software)", new GamePublisher("Quicksilva (Argus Press Software)"));
        publishers.put("Quicksilva Ltd.", new GamePublisher("Quicksilva Ltd."));
        publishers.put("Rabbit", new GamePublisher("Rabbit"));
        publishers.put("Rabbit Software", new GamePublisher("Rabbit"));
        publishers.put("Rack It (Hewson)", new GamePublisher("Rack It (Hewson)"));
        publishers.put("Rack-It", new GamePublisher("Rack-It"));
        publishers.put("Rack-It (Hewson Consultants Ltd.)", new GamePublisher("Rack-It (Hewson Consultants Ltd.)"));
        publishers.put("Rack-It (Hewson)", new GamePublisher("Rack-It (Hewson)"));
        publishers.put("Rack-it", new GamePublisher("Rack-it"));
        publishers.put("Rainbird", new GamePublisher("Rainbird"));
        publishers.put("Rainbird (Graftgold)", new GamePublisher("Rainbird (Graftgold)"));
        publishers.put("Rainbow Arts", new GamePublisher("Rainbow Arts"));
        publishers.put("Reaktör Software", new GamePublisher("Reaktör Software"));
        publishers.put("Richard Shepherd Software", new GamePublisher("Richard Shepherd Software"));
        publishers.put("Ricochet", new GamePublisher("Ricochet"));
        publishers.put("Ricochet (Mastertronic)", new GamePublisher("Ricochet (Mastertronic)"));
        publishers.put("Rino Marketing Ltd.", new GamePublisher("Rino Marketing Ltd."));
        publishers.put("Romik", new GamePublisher("Romik"));
        publishers.put("Romik Software", new GamePublisher("Romik Software"));
        publishers.put("Romik Software Ltd", new GamePublisher("Romik Software Ltd"));
        publishers.put("SNK Electrocoin", new GamePublisher("SNK Electrocoin"));
        publishers.put("SSI", new GamePublisher("SSI"));
        publishers.put("Screen 7", new GamePublisher("Screen 7"));
        publishers.put("Sega", new GamePublisher("Sega"));
        publishers.put("Sierra Online", new GamePublisher("Sierra Online"));
        publishers.put("Sierra Games", new GamePublisher("Sierra Games"));
        publishers.put("SilverTime", new GamePublisher("SilverTime"));
        publishers.put("Silverbird", new GamePublisher("Silverbird"));
        publishers.put("Silverbird / Probe Software", new GamePublisher("Silverbird / Probe Software"));
        publishers.put("Silverrock Production", new GamePublisher("Silverrock Production"));
        publishers.put("Softek", new GamePublisher("Softek"));
        publishers.put("Software Projects", new GamePublisher("Software Projects"));
        publishers.put("Software Projects Ltd.", new GamePublisher("Software Projects Ltd."));
        publishers.put("Solar Software", new GamePublisher("Solar Software"));
        publishers.put("Starlight Software", new GamePublisher("Starlight Software"));
        publishers.put("Starvision", new GamePublisher("Starvision"));
        publishers.put("Statesoft", new GamePublisher("Statesoft"));
        publishers.put("Statesoft Ltd.", new GamePublisher("Statesoft Ltd."));
        publishers.put("Storm / The Sales Curve", new GamePublisher("Storm / The Sales Curve"));
        publishers.put("Streetwise", new GamePublisher("Streetwise"));
        publishers.put("Summit", new GamePublisher("Summit"));
        publishers.put("Summit Software", new GamePublisher("Summit Software"));
        publishers.put("Superior Software Ltd.", new GamePublisher("Superior Software Ltd."));
        publishers.put("Supersoft", new GamePublisher("Supersoft"));
        publishers.put("Synapse Software", new GamePublisher("Synapse Software"));
        publishers.put("System 3", new GamePublisher("System 3"));
        publishers.put("System 3 Software", new GamePublisher("System 3 Software"));
        publishers.put("TV Games", new GamePublisher("TV Games"));
        publishers.put("Taskset", new GamePublisher("Taskset"));
        publishers.put("Taskset Ltd.", new GamePublisher("Taskset Ltd."));
        publishers.put("Tengen", new GamePublisher("Tengen"));
        publishers.put("Tengen/Domark", new GamePublisher("Tengen/Domark"));
        publishers.put("Terminal Software", new GamePublisher("Terminal Software"));
        publishers.put("Thalamus", new GamePublisher("Thalamus"));
        publishers.put("Thalion", new GamePublisher("Thalion"));
        publishers.put("The Edge", new GamePublisher("The Edge"));
        publishers.put("The Hit Squad", new GamePublisher("The Hit Squad"));
        publishers.put("Budget - The Hit Squad", new GamePublisher("Budget - The Hit Squad"));
        publishers.put("The Sales Curve", new GamePublisher("The Sales Curve"));
        publishers.put("Thor Computer Software", new GamePublisher("Thor Computer Software"));
        publishers.put("Thorn EMI Computer Software", new GamePublisher("Thorn EMI Computer Software"));
        publishers.put("Titus Software", new GamePublisher("Titus Software"));
        publishers.put("Top Ten Hits", new GamePublisher("Top Ten Hits"));
        publishers.put("Tymac Software", new GamePublisher("Tymac Software"));
        publishers.put("Tynesoft", new GamePublisher("Tynesoft"));
        publishers.put("U.S. Gold", new GamePublisher("U.S. Gold"));
        publishers.put("U.S. Gold Ltd.", new GamePublisher("U.S. Gold"));
        publishers.put("UK Gold", new GamePublisher("UK Gold"));
        publishers.put("UMI", new GamePublisher("UMI"));
        publishers.put("US Gold", new GamePublisher("US Gold"));
        publishers.put("US Gold (Artech Digital)", new GamePublisher("US Gold (Artech Digital)"));
        publishers.put("US Gold (Bally Midway)", new GamePublisher("US Gold (Bally Midway)"));
        publishers.put("US Gold (Cosmi)", new GamePublisher("US Gold (Cosmi)"));
        publishers.put("US Gold (Epyx)", new GamePublisher("US Gold (Epyx)"));
        publishers.put("US Gold (Sydney Development)", new GamePublisher("US Gold (Sydney Development)"));
        publishers.put("US Gold (Sydney Products)", new GamePublisher("US Gold (Sydney Products)"));
        publishers.put("US Gold (Synapse Software)", new GamePublisher("US Gold (Synapse Software)"));
        publishers.put("US Gold (Synsoft)", new GamePublisher("US Gold (Synsoft)"));
        publishers.put("US Gold / Capcom", new GamePublisher("US Gold / Capcom"));
        publishers.put("US Gold / Topo Soft", new GamePublisher("US Gold / Topo Soft"));
        publishers.put("Ubi-Soft", new GamePublisher("Ubi-Soft"));
        publishers.put("Ubisoft", new GamePublisher("Ubisoft"));
        publishers.put("UBI Soft", new GamePublisher("Ubisoft"));
        publishers.put("Ultimate", new GamePublisher("Ultimate"));
        publishers.put("United Microware Industries Inc.", new GamePublisher("United Microware Industries Inc."));
        publishers.put("Unknown", new GamePublisher("Unknown"));
        publishers.put("Virgin", new GamePublisher("Virgin"));
        publishers.put("Virgin Games", new GamePublisher("Virgin Games"));
        publishers.put("Virgin Games / Level 9 Computing", new GamePublisher("Virgin Games / Level 9 Computing"));
        publishers.put("Virgin Games Ltd.", new GamePublisher("Virgin Games Ltd."));
        publishers.put("Virgin Mastertronic", new GamePublisher("Virgin Mastertronic"));
        publishers.put("Virgin Mastertronic / Probe Software", new GamePublisher("Virgin Mastertronic / Probe Software"));
        publishers.put("Virgin Interactive", new GamePublisher("Virgin Interactive"));
        publishers.put("Virgin Mastertronic Ltd.", new GamePublisher("Virgin Mastertronic Ltd."));
        publishers.put("Visions Software Factory", new GamePublisher("Visions Software Factory"));
        publishers.put("Vivid Image", new GamePublisher("Vivid Image"));
        publishers.put("Viz Design", new GamePublisher("Viz Design"));
        publishers.put("Voyager", new GamePublisher("Voyager"));
        publishers.put("Walt Disney Company", new GamePublisher("Walt Disney Company"));
        publishers.put("Your Commodore", new GamePublisher("Your Commodore"));
        publishers.put("Zeppelin Games", new GamePublisher("Zeppelin Games"));
        publishers.put("Zeppelin Games Ltd.", new GamePublisher("Zeppelin Games"));
        //
        publishers.put("AGA", new GamePublisher("AGA"));
        publishers.put("Atari", new GamePublisher("Atari"));
        publishers.put("ECS", new GamePublisher("ECS"));
        publishers.put("Budget - GBH", new GamePublisher("Budget - GBH"));
        publishers.put("Telarium", new GamePublisher("Telarium"));
        publishers.put("Timeworks", new GamePublisher("Timeworks"));
        publishers.put("Trillium", new GamePublisher("Trillium"));
        // SegaCD
        publishers.put("Absolute Entertainment", new GamePublisher("Absolute Entertainment"));
        publishers.put("Acclaim Entertainment", new GamePublisher("Acclaim Entertainment"));
        publishers.put("American Laser Games", new GamePublisher("American Laser Games"));
        publishers.put("Arena Entertainment", new GamePublisher("Arena Entertainment"));
        publishers.put("Asmik", new GamePublisher("Asmik"));
        publishers.put("Big Fun Games", new GamePublisher("Big Fun Games"));
        publishers.put("Bignet USA", new GamePublisher("Bignet USA"));
        publishers.put("Bridgestone Multimedia", new GamePublisher("Bridgestone Multimedia"));
        publishers.put("Core Design", new GamePublisher("Core Design"));
        publishers.put("JVC", new GamePublisher("JVC"));
        publishers.put("CSK", new GamePublisher("CSK"));
        publishers.put("Data West", new GamePublisher("Data West"));
        publishers.put("Digital Pictures", new GamePublisher("Digital Pictures"));
        publishers.put("Dynamix", new GamePublisher("Dynamix"));
        publishers.put("Extreme Entertainment", new GamePublisher("Extreme Entertainment"));
        publishers.put("FASA Interactive", new GamePublisher("FASA Interactive"));
        publishers.put("Game Arts", new GamePublisher("Game Arts"));
        publishers.put("GameTek", new GamePublisher("GameTek"));
        publishers.put("Hot B", new GamePublisher("Hot B"));
        publishers.put("Interplay", new GamePublisher("Interplay"));
        publishers.put("JVC Musical Industries", new GamePublisher("JVC Musical Industries"));
        publishers.put("Koei", new GamePublisher("Koei"));
        publishers.put("Masaya", new GamePublisher("Masaya"));
        publishers.put("Micro Cabin", new GamePublisher("Micro Cabin"));
        publishers.put("Micronet", new GamePublisher("Micronet"));
        publishers.put("Namco", new GamePublisher("Namco"));
        publishers.put("Nichibutsu", new GamePublisher("Nichibutsu"));
        publishers.put("Nihon Telenet", new GamePublisher("Nihon Telenet"));
        publishers.put("Telenet", new GamePublisher("Telenet"));
        publishers.put("Oldergames", new GamePublisher("Oldergames"));
        publishers.put("Phillips Interactive", new GamePublisher("Phillips Interactive"));
        publishers.put("Polydor", new GamePublisher("Polydor"));
        publishers.put("Vic Tokai", new GamePublisher("Vic Tokai"));
        publishers.put("Readysoft", new GamePublisher("Readysoft"));
        publishers.put("Renovation Products", new GamePublisher("Renovation Products"));
        publishers.put("Rocket Science Games", new GamePublisher("Rocket Science Games"));
        publishers.put("Sammy Studios", new GamePublisher("Sammy Studios"));
        publishers.put("Tec Toy", new GamePublisher("Tec Toy"));
        publishers.put("SIMS", new GamePublisher("SIMS"));
        publishers.put("Software Toolworks", new GamePublisher("Software Toolworks"));
        publishers.put("Sony Imagesoft", new GamePublisher("Sony Imagesoft"));
        publishers.put("Sony Music Entertainment", new GamePublisher("Sony Music Entertainment"));
        publishers.put("Spectrum Holobyte", new GamePublisher("Spectrum Holobyte"));
        publishers.put("Strategic Simulations, Inc.", new GamePublisher("Strategic Simulations, Inc."));
        publishers.put("Taito", new GamePublisher("Taito"));
        publishers.put("TakerUCO", new GamePublisher("TakerUCO"));
        publishers.put("Tecmo", new GamePublisher("Tecmo"));
        publishers.put("Time Warner", new GamePublisher("Time Warner"));
        publishers.put("Time Warner Interactive", new GamePublisher("Time Warner Interactive"));
        publishers.put("Victor Interactive", new GamePublisher("Victor Interactive"));
        publishers.put("Wolf Tea", new GamePublisher("Wolf Tea"));
        publishers.put("Wolf Team", new GamePublisher("Wolf Team"));
        publishers.put("Working Designs", new GamePublisher("Working Designs"));
        // Atari ST
        publishers.put("Sizzlers", new GamePublisher("Sizzlers"));
        publishers.put("Action Sixteen", new GamePublisher("Action Sixteen"));
        publishers.put("Smash 16", new GamePublisher("Smash 16"));
        publishers.put("16 Blitz", new GamePublisher("16 Blitz"));
        publishers.put("Klassix", new GamePublisher("Klassix"));
        publishers.put("Buzz", new GamePublisher("Buzz"));
        publishers.put("Fox Hits", new GamePublisher("Fox Hits"));
        publishers.put("Action Sixteen", new GamePublisher("Action Sixteen"));
        publishers.put("Pocket Soft", new GamePublisher("Pocket Soft"));
        // Commodore
        publishers.put("Software Country", new GamePublisher("Software Country"));
        publishers.put("Global Software", new GamePublisher("Global Software"));
        publishers.put("Paradox", new GamePublisher("Paradox"));
        publishers.put("Starbyte", new GamePublisher("Starbyte"));
        publishers.put("Starbyte Software", new GamePublisher("Starbyte"));
        // Nes
        publishers.put("RCM Group", new GamePublisher("RCM Group"));
        publishers.put("Gluk Video", new GamePublisher("Gluk Video")); // Pirata
        publishers.put("NTDEC, Gluk Video", new GamePublisher("NTDEC, Gluk Video")); // Pirata
        publishers.put("Sachen", new GamePublisher("Sachen"));
        // Gameboy Advance
        publishers.put("Zoo Digital", new GamePublisher("Zoo Digital"));
        publishers.put("Vivendi", new GamePublisher("Vivendi"));
    }

    private GamePublisher(String publisher) {
        this.publisher = publisher;
    }

    public static boolean isPublisher(String name) {
        return publishers.containsKey(name);
    }

    public static GamePublisher fromName(String name) {
        GamePublisher pub = publishers.get(name);
        if (pub == null) {
            //TODO: Criar uma exception
            throw new IllegalArgumentException(name);
        }
        return pub;
    }

    public static GamePublisher getPublisher(String name) {
        return publishers.get(name);
    }

    @Override
    public String toString() {
        return this.publisher;
    }
}
